GET https://api.weixin.qq.com/sns/jscode2session
Content-Type:application/x-www-form-urlencoded
appid=wx1c759351c7cfba06
serect=7fbaf60f8020696ace7a765bc16dd846
js_code=0a32vyll2qIvLd4ZzUll2mlhSl32vylI
grant_type=authorization_code