sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: ljj20020623

  wechat:
    appid: wx1c759351c7cfba06
    secret: 7fbaf60f8020696ace7a765bc16dd846

  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10

  alioss:
    endpoint: oss-cn-chengdu.aliyuncs.com
    access-key-id: LTAI5tKApHtyu8eFrXw3M2Cs
    access-key-secret: gZEBVetC5Crk9sk31nSkKXwq8PiHYz
    bucket-name: sky-take-out-ljj01





