sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: ljj20020623

  alioss:
    endpoint: oss-cn-chengdu.aliyuncs.com
    access-key-id: LTAI5tKApHtyu8eFrXw3M2Cs
    access-key-secret: gZEBVetC5Crk9sk31nSkKXwq8PiHYz
    bucket-name: sky-take-out-ljj01

